# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/Dell/fpga/uart/uart_proj/integrated code/integration_uart/integration_uart.srcs/constrs_1/imports/receiver/uart_constraints.xdc

# IP: C:/Users/Dell/fpga/uart/uart_proj/integrated code/integration_uart/integration_uart.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# IP: C:/Users/Dell/fpga/uart/uart_proj/integrated code/integration_uart/integration_uart.srcs/sources_1/ip/ila_0/ila_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ila_0 || ORIG_REF_NAME==ila_0} -quiet] -quiet

# IP: C:/Users/Dell/fpga/uart/uart_proj/integrated code/integration_uart/integration_uart.srcs/sources_1/ip/vio_0/vio_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vio_0 || ORIG_REF_NAME==vio_0} -quiet] -quiet
